### ISSUE TITLE
Return wrong path

### ISSUE THREAD

**Issue by HuuNguyen312** [HBiSoft/PickiT#35] opened 2021-02-27 07:47 UTC
**Return wrong path**
- After choosing a file from Intent in KakaotalkDownload, but data from pickiT.getPath in Download folder
- So, I received FileNotFoundException.

**Expect**
Return path: xxx/KakaotalkDownload/filename

**Can it be reproduced in demo app**
Yes

**Device information**
- Samsung Note 10 Lite
- SDK version: 29 (Android 10)

**Screenshots**

![Screenshot_20210227-163755_PickiT example](https://user-images.githubusercontent.com/9895294/109381036-76851880-790a-11eb-84f2-b7f6ea630c6b.jpg)
![Screenshot_20210227-163730_My Files](https://user-images.githubusercontent.com/9895294/109381038-77b64580-790a-11eb-85bd-8916bb19a421.jpg)

**Comment by HBiSoft** [comment] 2021-03-02 06:17
I downloaded KakaoTalk, downloaded a file I sent to myself and tested the path in the demo application. I get the correct path: `/storage/emulated/0/KakaotalkDownload/test.mp4`.

Please share your `Intent`. I see that you select a `.pdf` file, but the demo application gives you an option to select a video, so you must have changed the `Intent`.

**Comment by HuuNguyen312** [comment] 2021-03-02 07:16
This is my Intent

```
    private void openGallery() {
        //  first check if permissions was granted
        if (checkSelfPermission()) {
            Intent intent = new Intent();
            intent.setType("*/*");
            intent.setAction(Intent.ACTION_GET_CONTENT);
            intent.addCategory(Intent.CATEGORY_OPENABLE);
            intent.putExtra("return-data", true);
            intent.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);
            startActivityForResult(intent, SELECT_VIDEO_REQUEST);
        }
    }
```

This is block code in my case
`return Environment.getExternalStorageDirectory().toString() + "/Download/"+ fileName;`

![image](https://user-images.githubusercontent.com/9895294/109611343-acbbd580-7b60-11eb-82fc-e0317f07a3f5.png)

I tried using this file by another app (Telegram, kakaotalk, ...). This file can still be read and sent normally.
I can add more log to any code if you need.

Thanks

**Comment by HBiSoft** [comment] 2021-03-06 17:23
I was not able to reproduce this. Please download the original demo application (https://github.com/HBiSoft/PickiT/releases/download/0.1.14/PickiTDemo.apk) and select a video file instead of a pdf. Let me know what path you then get.

**Comment by HBiSoft** [comment] 2021-03-14 05:39
Closing until more information (asked above) is provided.

**Closed by HBiSoft** 2021-03-14 05:39 UTC
Labels: Needs more info
