### ISSUE TITLE
 does not work in api 21(Lollipop)

### ISSUE THREAD

**Issue by mohamadIT2018** [HBiSoft/PickiT#28] opened 2020-09-11 09:52 UTC

**Comment by HBiSoft** [comment] 2020-09-11 11:25
Please provide more information. 

Where do you select a file from?
Have you tested using the demo application?
What does your log say?

As the issue is now it is impossible for me to help you.

**Comment by HBiSoft** [comment] 2020-09-12 15:23
Closing until more information is provided.

**Closed by HBiSoft** 2020-09-12 15:23 UTC
Labels: Needs more info
